export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function FavoritesLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>;
}
